FROM ubuntu:trusty

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    build-essential \
    python-dev \
    wget \
    git-core \
    curl \
    ruby-dev \
    rpm \
    zip \
    python-pip \
    python-apt

RUN gem install fpm
RUN pip install boto influxdb

# Install go
ENV GO_VERSION 1.4.3
ENV GO_ARCH amd64
RUN wget -q https://storage.googleapis.com/golang/go${GO_VERSION}.linux-${GO_ARCH}.tar.gz; \
   tar -C /usr/local/ -xf /go${GO_VERSION}.linux-${GO_ARCH}.tar.gz ; \
   rm /go${GO_VERSION}.linux-${GO_ARCH}.tar.gz
ENV PATH /usr/local/go/bin:$PATH

# Create cross-compile toolchain
ENV GOPATH /usr/local/go
WORKDIR $GOPATH/src
RUN GOOS=linux GOARCH=amd64 /usr/local/go/src/make.bash --no-clean
RUN GOOS=linux GOARCH=386 /usr/local/go/src/make.bash --no-clean
RUN GOOS=linux GOARCH=arm /usr/local/go/src/make.bash --no-clean
RUN GOOS=darwin GOARCH=amd64 /usr/local/go/src/make.bash --no-clean
RUN GOOS=darwin GOARCH=386 /usr/local/go/src/make.bash --no-clean
RUN GOOS=windows GOARCH=amd64 /usr/local/go/src/make.bash --no-clean
RUN GOOS=windows GOARCH=386 /usr/local/go/src/make.bash --no-clean

# Create volume structure
ENV GOPATH /root/go
ENV PATH $GOPATH/bin:$PATH
ENV PROJECT_DIR $GOPATH/src/github.com/influxdata/influxdb
RUN mkdir -p $PROJECT_DIR

WORKDIR $PROJECT_DIR
VOLUME $PROJECT_DIR
ENTRYPOINT [ "/root/go/src/github.com/influxdata/influxdb/build.py" ]
